from django.conf.urls import patterns, url

urlpatterns = patterns('searcher.views',
    url(r'^zc$', 'index_zc', name='index_zc'),
    url(r'^my$', 'index_zc', name='index_zc'),
    url(r'^search_zc$', 'search_zc', name='search_zc'),
    url(r'^auth_register$', 'auth_register', name='auth_register'),
    url(r'^$', 'index_zc', name='index_jf'),
    url(r'^login/$',  'login', name='login'),
    url(r'^generate/$', 'generate', name='generate'),
    url(r'sendSMS/$','sendSMS',name='sendSMS'),
    url(r'^project_reply/(?P<project_id>\d+)/$', 'project_reply', name='project_reply'),
    url(r'^add_attion/(?P<objectid>\d+)/$',  'add_attion', name='add_attion'),
    url(r'^cancel_attion/(?P<objectid>\d+)/$',  'cancel_attion', name='cancel_attion'),
    url(r'^add_attion_investor/$',  'add_attion_investor', name='add_attion_investor'),
    url(r'^cancel_attion_investor/$',  'cancel_attion_investor', name='cancel_attion_investor'),
    url(r'^logout/$',  'logout', name='logout'),
    url(r'^do_search/$',  'do_search', name='do_search'),
    url(r'^do_result/$',  'do_result', name='do_result'),
    url(r'^do_reminder/$',  'do_reminder', name='do_reminder'),
    url(r'^register/$',  'register', name='register'),
    url(r'^userinfo/$',  'userinfo', name='userinfo'),
                       url(r'^userinfo/$',  'userinfo', name='userinfo'),
                       url(r'^manage/$',  'manage', name='manage'),
                       url(r'^authentication/$',  'authentication', name='authentication'),
                       url(r'^safe_center/$',  'safe_center', name='safe_center'),
                       url(r'^info/$',  'info', name='info'),
                       url(r'^invitation/$',  'invitation', name='invitation'),
    url(r'^contact/$',  'contact', name='contact'),
   url(r'^join/$',  'join', name='join'),
   url(r'^media/$',  'media', name='media'),
   url(r'^partner/$',  'partner', name='partner'),

    url(r'getverifycode/$', 'verifycode', name='verifycode'),
    url(r'forgetpw/$', 'forgetpw', name='forgetpw'),

    url(r'intermediary/(?P<objectid>\d+)/$', 'intermediary', name='intermediary'),
    url(r'^invest_pr/(?P<objectid>\d+)/$',  'invest_pr', name='invest_pr'),

    url(r'^agreement/$',  'agreement', name='agreement'),
    url(r'^safecenter/$',  'safecenter', name='safecenter'),
    url(r'^change_phone_number/$',  'change_phone_number', name='change_phone_number'),
    url(r'^guide/$',  'guide', name='guide'),
    url(r'^about/$',  'about', name='about'),
    url(r'^investor/$',  'investor', name='investor'),
    url(r'^get_status/$','get_status',name='get_status'),
    url(r'^invested/$',  'invested', name='invested'),
    url(r'^search_investor/$',  'search_investor', name='search_investor'),
    url(r'^safety/(?P<objectid>\d+)/$',  'safety', name='safety'),
    url(r'^investor_info/(?P<objectid>\d+)/$',  'investor_info', name='investor_info'),
    url(r'^contact_us/$',  'contact_us', name='contact_us'),
    url(r'^prodetails/(?P<objectid>\d+)/$',  'prodetails', name='prodetails'),

    url(r'^checkvcode/$',  'checkvcode', name='checkvcode'),
    url(r'^search/$',  'search', name='search'),
    url(r'^search_project/$',  'search_project', name='search_project'),
    url(r'^project/$',  'project', name='project'),
    url(r'^publish/$',  'publish', name='publish'),
    url(r'^checkuser/$',  'checkuser', name='checkuser'),
    url(r'^checkuser_phone/$',  'checkuser_phone', name='checkuser_phone'),
    url(r'^investor_detail/$',  'investor_detail', name='investor_detail'),
    url(r'^checkvcode/$',  'checkvcode', name='checkvcode'),
    url(r'^checksmscode/$',  'checksmscode', name='checksmscode'),
    url(r'^uploadify_script/(?P<objectid>\d+)/$', 'uploadify_script'),
    url(r'^delete_uploadfile/$','profile_delte')

)

urlpatterns += patterns('searcher.views',
    url(r'^send_smscode/$',  'send_smscode', name='send_smscode'),
    url(r'^send_smscode_modify/$',  'send_smscode_modify', name='send_smscode_modify'),
        )
urlpatterns += patterns('searcher.agreement_views',
    url(r'^write/$',  'writeagreement', name='writeagreement'),
        )
urlpatterns += patterns('searcher.viewss',
    url(r'^search_zc$', 'search_zc', name='search_zc'),
    url(r'^mobile/$', 'index_m', name='index_m'),
    url(r'^mobile/login/$',  'login_m', name='login_m'),
    url(r'^mobile/register/$',  'register_m', name='register_m'),
    url(r'^mobile/userinfo/$',  'userinfo_m', name='userinfo_m'),
    url(r'^mobile/project/(?P<objectid>\d+)/$',  'project_m', name='project_m'),
    url(r'^mobile/investor/$',  'investor_m', name='investor_m'),
    url(r'^mobile/guide/$',  'guide_m', name='guide_m'),
    url(r'^mobile/about_us/$',  'about_us_m', name='about_us_m'),
        )
